export const homeObjOne = {
    id: 'about',
    lightBg: false,
    lightText: true,
    lightTextDesc: true,
    topLine: 'Premium Bank',
    headline: 'Unlimited Transaction with zero fees',
    description: 'Get access to our exclusive app that allows you to send unliited transactions without getting charged any fees.',
    buttonLabel: 'Get started',
    imgStart: true,
    img: require('../../images/svg1.svg').default,
    alt: 'Car',
    dark: true,
    primary: true,
    darkText: false,
}

export const homeObjTwo = {
    id: 'discover',
    lightBg: true,
    lightText: false,
    lightTextDesc: false,
    topLine: 'Log In Acces',
    headline: 'Log in to your accnout at any time',
    description: 'We have you covered no matter where you are located. ALl you need is an internet connection and a phone or computer.',
    buttonLabel: 'Learn More',
    imgStart: false,
    img: require('../../images/svg2.svg').default,
    alt: 'Car',
    dark: false,
    primary: false,
    darkText: true,
}

export const homeObjThree = {
    id: 'services',
    lightBg: false,
    lightText: true,
    lightTextDesc: true,
    topLine: 'Premium Bank',
    headline: 'Unlimited Transaction with zero fees',
    description: 'Get access to our exclusive app that allows you to send unliited transactions without getting charged any fees.',
    buttonLabel: 'Start Now',
    imgStart: true,
    img: require('../../images/svg3.svg').default,
    alt: 'Paper',
    dark: true,
    primary: true,
    darkText: false,
}

export const homeObjFour = {
    id: 'signup',
    lightBg: true,
    lightText: false,
    lightTextDesc: false,
    topLine: 'Premium Bank',
    headline: 'Unlimited Transaction with zero fees',
    description: 'Get access to our exclusive app that allows you to send unliited transactions without getting charged any fees.',
    buttonLabel: 'Start Now',
    imgStart: false,
    img: require('../../images/svg3.svg').default,
    alt: 'Paper',
    dark: false,
    primary: false,
    darkText: true,
}